name: atom-unoffical # you probably want to 'snapcraft register <name>'
version: '1.40' # just for humans, typically '1.2+git' or '1.3.2'
summary: A hackable text editor for the 21st Century.
 # 79 char long summary
description: |
  Atom is a free and open source text editor that is modern,
  approachable, and hackable to the core.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

parts:
  atom:
    plugin: nodejs
    node-engine: '8.17.0'
    source: https://github.com/enjoysoftware/atom-unoffical
    source-type: git
    override-build: |
      set -x
      ARCH=$(dpkg --print-architecture)
      DEB_PATH=out/atom-$(ARCH).deb
      if [ "$(ARCH)" = "armhf" ]; then
        export npm_config_arch=armv7l
      fi
      script/build --create-debian-package
      dpkg -x $(DEB_PATH) $SNAPCRAFT_PART_INSTALL
      grep Icon $SNAPCRAFT_PART_INSTALL/usr/share/applications/atom.desktop
      sed -i 's|Icon=atom|Icon=${SNAP}/usr/share/pixmaps/atom\.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/atom.desktop
      grep Icon $SNAPCRAFT_PART_INSTALL/usr/share/applications/atom.desktop
    build-packages:
      - curl
    stage-packages:
      - fcitx-frontend-gtk3
      - libappindicator3-1
      - libasound2
      - libcurl3-gnutls
      - libgconf-2-4
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
  atom-launch:
    plugin: dump
    source: bin/
    prepare: |
      chmod +x bin/atom-launch
apps:
  atom:
    command: bin/atom-launch ${SNAP}/usr/share/atom/atom
    desktop: usr/share/applications/atom.desktop
    environment:
      DISABLE_WAYLAND: 1

  apm:
    command: bin/atom-launch ${SNAP}/usr/bin/apm


